# Generated by Django 4.2.27 on 2026-05-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
