# Generated by Django 4.2.13 on 2025-03-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimages_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
