# Generated by Django 4.2.13 on 2025-03-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='images',
            new_name='image',
        ),
    ]
