# Generated by Django 4.2.27 on 2025-12-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0002_alter_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='Somos a esperanca', max_length=150),
            preserve_default=False,
        ),
    ]
