# Generated by Django 4.2.27 on 2025-12-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0005_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, default='About us', max_length=150),
        ),
    ]
