# Generated by Django 4.2.27 on 2025-12-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0006_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='banner_images/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='customize.slider')),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
