# Generated by Django 4.2.27 on 2025-12-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0007_banner_delete_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='slider',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
