# Generated by Django 4.2.27 on 2025-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0008_remove_banner_slider_delete_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, default='About us', max_length=40),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
