# Generated by Django 4.2.27 on 2026-05-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0009_alter_about_title_alter_banner_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlistitem',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
