# Generated by Django 4.2.27 on 2026-05-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0010_footerlistitem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlistitem',
            old_name='url',
            new_name='link',
        ),
    ]
